services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    networks:
      - notes-net

  backend:
    build:
      context: ./notes-backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/notesdb
      - PORT=5000
    depends_on:
      - mongo
    networks:
      - notes-net

  frontend:
    build:
      context: ./notes-frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - notes-net

volumes:
  mongo_data:

networks:
  notes-net:
    driver: bridge
